# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:
        # Inputs the workflow accepts.
        inputs:
            name:
                # Friendly description to be shown in the UI instead of 'name'
                description: 'CI/CD to greet'
                # Default value if no value is explicitly provided
                default: 'Build'
                # Input has to be provided for the workflow to run
                required: true
                # The data type of the input
                type: string
jobs:
    start_stage:
        runs-on: ubuntu-latest
        steps:
            - name: Slit ref to array.
              id: split
              uses: jungwinter/split@v2
              with:
                  msg: ${{ github.ref_name }}
                  separator: '@'
            - name: Send greeting
              run: echo "Hello ${{ steps.split.outputs._0 }}, I'm in build stage"
    code_quality:
        needs: start_stage
        runs-on: ubuntu-latest
        steps:
            - name: Slit ref to array.
              id: split
              uses: jungwinter/split@v2
              with:
                  msg: ${{ github.ref_name }}
                  separator: '@'
            - name: Checkout branch
              uses: actions/checkout@v3
              with:
                  ref: ${{ steps.split.outputs._0 }}
            - name: Sonar scanner backend
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  projectBaseDir: ./src
                  args: >
                      -Dsonar.projectKey=ci-cd-github-actions-test-1
                      -Dsonar.branch.name=${{ steps.split.outputs._0 }}
                      -Dsonar.sourceEncoding=UTF-8
                      -Dsonar.cobol.copy.directories=copybooks
                      -Dsonar.cobol.file.suffixes=cbl,cpy
                      -Dsonar.cobol.copy.suffixes=cpy
                      -Dsonar.flex.cobertura.reportPath=coverage-report/coverage-cobertua-flex.xml
                      -Dsonar.exclusions=**/__tests__/**,**/mocks/** -Dsonar.pli.marginLeft=2
                      -Dsonar.pli.marginRight=0
                      -Dsonar.organization=river248
            - name: Get sonar report
              id: sonar_report
              run: |
                  echo "report=$(curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=ci-cd-github-actions-test-1\&branch=${{ steps.split.outputs._0 }})" >> "$GITHUB_OUTPUT"
            - name: Push metric
              run: |
                  curl -d '{"repository":"ci-cd-github-actions-test-1","stage":"build","executionId":"${{ github.run_id }}","metricName":"Code Quality","appMetricName":"default","reportUrl":"https://sonarcloud.io/summary/new_code?branch=${{ steps.split.outputs._0 }}&id=ci-cd-github-actions-test-1","data":${{ toJSON(steps.sonar_report.outputs.report) }}}' \
                    -H "Content-Type: application/json" \
                    -X POST https://ci-cd-github-actions-test.onrender.com/v1/metric/push-metric
    unit_tests:
        needs: start_stage
        runs-on: ubuntu-latest
        steps:
            - name: Slit ref to array.
              id: split
              uses: jungwinter/split@v2
              with:
                  msg: ${{ github.ref_name }}
                  separator: '@'
            - name: Checkout branch
              uses: actions/checkout@v3
              with:
                  ref: ${{ steps.split.outputs._0 }}
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Run unit test
              run: |
                  npm ci
                  npm run test
            - name: Get report unit tests
              if: ${{ always() }}
              id: unit_test_report
              run: |
                  echo "report=$(cat ./junit.json)" >> "$GITHUB_OUTPUT"
            - name: Push metric
              if: ${{ always() }}
              run: |
                  curl -d '{"repository":"ci-cd-github-actions-test-1","stage":"build","executionId":"${{ github.run_id }}","metricName":"Unit Tests","appMetricName":"default","data": "{\"numPassedTests\": ${{ fromJSON(steps.unit_test_report.outputs.report).numPassedTests }}, \"numTotalTests\": ${{ fromJSON(steps.unit_test_report.outputs.report).numTotalTests }}}"}' \
                    -H "Content-Type: application/json" \
                    -X POST https://ci-cd-github-actions-test.onrender.com/v1/metric/push-metric
    unit_test_coverage:
        needs: start_stage
        runs-on: ubuntu-latest
        steps:
            - name: Slit ref to array.
              id: split
              uses: jungwinter/split@v2
              with:
                  msg: ${{ github.ref_name }}
                  separator: '@'
            - name: Checkout branch
              uses: actions/checkout@v3
              with:
                  ref: ${{ steps.split.outputs._0 }}
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Run unit test coverage
              run: |
                  npm ci
                  npm run test
            - name: Get coverage report
              if: ${{ always() }}
              id: coverage_report
              run: |
                  {
                    echo 'report<<EOF'
                    cat ./coverage-summary.json
                    echo EOF
                  } >> "$GITHUB_OUTPUT"
            - name: Push metric
              run: |
                  curl -d '{"repository":"ci-cd-github-actions-test-1","stage":"build","executionId":"${{ github.run_id }}","metricName":"Unit Test Coverage","appMetricName":"default","data": "{\"actual\": ${{ fromJSON(steps.coverage_report.outputs.report).total.lines.covered }}, \"total\": ${{ fromJSON(steps.coverage_report.outputs.report).total.lines.total }}}"}' \
                    -H "Content-Type: application/json" \
                    -X POST https://ci-cd-github-actions-test.onrender.com/v1/metric/push-metric
    finish_stage:
        if: ${{ always() }}
        needs: [start_stage, code_quality, unit_tests, unit_test_coverage]
        runs-on: ubuntu-latest
        steps:
            - name: Slit ref to array.
              id: split
              uses: jungwinter/split@v2
              with:
                  msg: ${{ github.ref_name }}
                  separator: '@'
            - name: Checkout branch
              uses: actions/checkout@v3
              with:
                  ref: ${{ steps.split.outputs._0 }}
            - name: Trigger Test
              if: needs.code_quality.result != 'cancelled' && needs.unit_tests.result != 'cancelled'
              run: |
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: ${{ secrets.BEARER_TOKEN }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/river248/ci-cd-github-actions-test-1/actions/workflows/test.yml/dispatches \
                    -d '{"ref":"${{ github.ref_name }}","inputs":{"name":"Test"}}'
